# Generated by Django 4.2.5 on 2023-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'cleanlist',
            },
        ),
        migrations.CreateModel(
            name='DirtySEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirty_seo_metadata', models.TextField()),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'dirty_seo_metadata',
            },
        ),
        migrations.CreateModel(
            name='ParsedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('favicon', models.TextField()),
                ('locale', models.TextField()),
                ('type', models.TextField()),
                ('names', models.TextField()),
                ('emails', models.TextField()),
                ('phone_numbers', models.TextField()),
                ('ip_address', models.TextField()),
                ('location', models.TextField()),
                ('keywords', models.TextField()),
            ],
            options={
                'db_table': 'parsed_output_table',
            },
        ),
    ]
